version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: food_store_db
    environment:
      POSTGRES_DB: food_store
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust  
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: